package io.github.catimental.diexample.exception;

public enum ErrorCode {
    DUPLICATE_LOGIN_ID,
    MEMBER_NOT_FOUND,
    INVALID_PASSWORD,
    WATCHLIST_NOT_FOUND,
    ALREADY_WACHLISTED,
    INVALID_PROGESS,
    PROGRESS_NOT_FOUND,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_REVOKED,
    REFRESH_TOKEN_EXPIRED,
    INVALID_WINDOW,
    LIKE_NOT_FOUND,
    RATING_NOT_FOUND,
    INVALID_RATING,
    RATE_LIMITED
}




